### ISSUE TITLE
load monaco from node_modules

### ISSUE THREAD

**Issue by khoshrou** [SurenAt93/monaco-react#12] opened 2019-08-11 20:20 UTC
Hi 
thank you for this awesome component, can you make it load monaco from node modules instead of cdn?

**Comment by SurenAt93** [comment] 2019-08-11 21:28
Hello, thank you for your feedback.

Unfortunately, in the current version, it's not possible.

But you can [notice](https://github.com/SurenAt93/monaco-react/blob/master/src/config/index.js#L4) that there is a config file and theoretically you can load it from where you want (wherever you have access to). I just need to make it customizable. It should be something like this:


```js
import { monaco } from '@monaco-editor/react';

monaco
  .config({...})
  .init()
...
```

So, you can load it for example from your public folder.
Can you load it from node_modules in that case?
It depends on your static server configuration.

I will make the `config` customizable in the next version and will keep you up to date here, for now, let it stay open.

**Comment by khoshrou** [comment] 2019-08-12 06:26
Hi again
That would be kind of essential consider you like to create an electron or a nwjs desktop app

**Comment by SurenAt93** [comment] 2019-08-12 13:55
I absolutely agree, so I will do it first.

**Comment by zzeebbii** [comment] 2019-08-15 13:24
Hi @SurenAt93 
Do you have any idea when this new version will be available with configurable configuration?

**Comment by SurenAt93** [comment] 2019-08-15 14:26
Hi @zzeebbii, I hope it will be ready tomorrow.

**Comment by SurenAt93** [comment] 2019-08-16 17:36
Hi guys. The new version is here. (v1.2.0).

You can modify config as shown [here](https://github.com/SurenAt93/monaco-react/blob/master/README.md#config).

#### For downloading monaco from your files

So, if you are using CRA, for example, you can install `monaco-editor` package:

```bash
yarn add monaco-editor # (npm install monaco-editor)
```
after that move/copy the minified (it's for an example) version of editor to your (CRA) public folder:

```bash
mv node_modules/monaco-editor/min/vs/ ./public
```
and now, by changing configs with the new api, you can load monaco files from your public folder:

```js
import { monaco } from './monaco-react/src';

monaco
  .config({
    urls: {
      monacoLoader: '/vs/loader.js',
      monacoBase: '/vs'
    },
  });
```

Please check it and let me know if it covers your cases. Thank you!

**Comment by zzeebbii** [comment] 2019-08-16 18:23
Hi @SurenAt93,
Thank you for such a quick update (Y). Yes, it will resolve the problem of loading from CDN and now we can load assets from disk which is quite good in many cases.

I know loading mechanism of `monaco-editor` is quite complex, but I was wondering if there is any possibility to just build one bundle instead of copying files and then referencing those files? Just curious :-)

**Comment by SurenAt93** [comment] 2019-08-17 10:52
Yes, of course, there is a way, to make a single bundle. But during making that very bundle we will need some extra webpack plugins, which is not "possible" in case of CRA; that's why this package/library exists.

**Comment by zzeebbii** [comment] 2019-08-17 10:56
Actually, I am not using CRA. I am building my bundles with manual webpack configuration that's why I was asking. I can include the `monaco-editor` in my bundle but then I'm not sure how should I use configuration with your package. I mean, does your plugin check first if `monaco` exists and use that or it always loads the monaco from configuration we provide like CDN or resource on disk.

**Comment by SurenAt93** [comment] 2019-08-17 11:00
If you are not using CRA, and you can customize your webpack configs, and also you are okay with a single bundle of monaco, so, in that case, there are other solutions/packages/libraries to do that:

Please find those libraries [here](https://github.com/SurenAt93/monaco-react#motivation)

**Comment by SurenAt93** [comment] 2019-08-18 10:38
@khoshrou could you please check the new version. And if it covers your case we can close the issue.

**Comment by khoshrou** [comment] 2019-08-18 16:38
Hi Suren
I just tested new version, its amazing.
it works as i expected. Thanks again.
I have a question
In your component we dont bundle monaco. do we loose any thing this way?

**Comment by SurenAt93** [comment] 2019-08-18 16:54
Of course no. It will work as expected. By avoiding bundling we avoid wepack configuration. Just it. Originally monaco worked without bundling; on the [official home page](https://microsoft.github.io/monaco-editor/) of monaco it works without bundles. (check the "network" section in the devtools to see more)

**Comment by khoshrou** [comment] 2019-08-18 17:16
I checked the network section and library is loaded from local folder
Again Thanks

**Closed** 2019-08-19 07:43 UTC

**Comment by lucid3v** [comment] 2019-08-21 20:58
> 
> 
> Hi guys. The new version is here. (v1.2.0).
> 
> You can modify config as shown [here](https://github.com/SurenAt93/monaco-react/blob/master/README.md#config).
> #### For downloading monaco from your files
> 
> So, if you are using CRA, for example, you can install `monaco-editor` package:
> 
> ```shell
> yarn add monaco-editor # (npm install monaco-editor)
> ```
> 
> after that move/copy the minified (it's for an example) version of editor to your (CRA) public folder:
> 
> ```shell
> mv node_modules/monaco-editor/min/vs/ ./public
> ```
> 
> and now, by changing configs with the new api, you can load monaco files from your public folder:
> 
> ```js
> import { monaco } from './monaco-react/src';
> 
> monaco
>   .config({
>     urls: {
>       monacoLoader: '/vs/loader.js',
>       monacoBase: '/vs'
>     },
>   });
> ```
> 
> Please check it and let me know if it covers your cases. Thank you!

Hi, where is the 
import { monaco } from './monaco-react/src'; 
coming from?

I can't seem to have this in my project. My package.json has 

@monaco-editor/react = "^1.2.1"
monaco-editor = "^0.17.1

**Comment by SurenAt93** [comment] 2019-08-21 21:04
Hello @lucid3v. Sorry, that was a typo, it should be `import { monaco } from '@monaco-editor/react';`

**Comment by lucid3v** [comment] 2019-08-21 21:21
> 
> 
> Hello @lucid3v. Sorry, that was a typo, it should be `import { monaco } from '@monaco-editor/react';`

Thanks! I'm getting further now. One more question... how do I render the Editor with the new import using:
import { monaco } from '@monaco-editor/react';`

my code(on my offline machine) is as this:

```
import {monaco as Editor} from "@monaco-editor/react"

Editor.config({
urls: {
monacoLoader: "/vs/loader.js",
monacoBase: "vs"
}
});

...further down...

return (
<Editor 
language="json"
height="90vh"
width="100%"
theme="light"
value="// some code"
/>
```

**Comment by SurenAt93** [comment] 2019-08-21 21:28
> > Hello @lucid3v. Sorry, that was a typo, it should be `import { monaco } from '@monaco-editor/react';`
> 
> Thanks! I'm getting further now. One more question... how do I render the Editor with the new import using:
> import { monaco } from '@monaco-editor/react';`
> 
> my code(on my offline machine) is as this:
> 
> ```
> import {monaco as Editor} from "@monaco-editor/react"
> 
> Editor.config({
> urls: {
> monacoLoader: "/vs/loader.js",
> monacoBase: "/vs"
> }
> });
> 
> ...further down...
> 
> return (
> <Editor 
> language="json"
> height="90vh"
> width="100%"
> theme="light"
> value="// some code"
> />
> ```

Your case will look like something like [this](https://codesandbox.io/s/monaco-editorreact---playground-pczh7?fontsize=14). Please check it out.

**Comment by elisherer** [comment] 2020-04-21 08:39
If you want a fresh copy of the latest installed `monaco-editor` use [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin):

```npm i -D copy-webpack-plugin```

Inside `webpack.config`:
```js
const CopyWebpackPlugin = require("copy-webpack-plugin");

// in the plugin section
new CopyWebpackPlugin([
  { from: "node_modules/monaco-editor/min/vs/", to: "vs" }
]),
```

**Comment by khoshrou** [comment] 2020-04-21 17:14
Do you say in this way we don't need to copy vs to public folder?
and how it's done in a (create-react-app) without ejecting?

**Comment by suren-atoyan** [comment] 2020-04-21 18:38
> Do you say in this way we don't need to copy vs to public folder?
> and how it's done in a (create-react-app) without ejecting?

I guess yes, it's about to avoid copying `vs` folder into `public` one.  But to be honest, I also don't understand how it will work with CRA.

**Comment by SivaKranthiKumar** [comment] 2020-04-22 03:30
What is the difference between
```javascript
monaco.config({
  urls: {
    monacoLoader: "/vs/loader.js",
    monacoBase: "/vs"
  }
});
```
and

```javascript
monaco.config({
  paths: {
    vs: '...',
  },
  'vs/nls' : {
    availableLanguages: {
      '*': 'de',
    },
  },
});
```

**Comment by benjaminbours** [comment] 2020-04-23 13:57
@suren-atoyan  There is something wrong with the CDN. I'm using the default config but it seems the CDN itself resolve badly this path, is that right and how is it possible? Do you have any workaround?

![Screenshot 2020-04-23 at 15 54 16](https://user-images.githubusercontent.com/8804297/80106882-b6f16880-857a-11ea-9c8f-15413d18c80d.png)

**Comment by benjaminbours** [comment] 2020-04-23 19:43
@suren-atoyan  I have tried this of course. I'm using the same cdn link that your demo,
<img width="1680" alt="Screenshot 2020-04-23 at 21 36 51" src="https://user-images.githubusercontent.com/8804297/80141979-bb357a00-85aa-11ea-9ab3-2c24a703908d.png">

But still the same issue so I don't understand.
<img width="618" alt="Screenshot 2020-04-23 at 21 38 54" src="https://user-images.githubusercontent.com/8804297/80142138-f9cb3480-85aa-11ea-95be-c9ae53b032f6.png">

I downgraded to use the same version as you on the demo, the 3.1.0. Same issue. The only thing I didn't tried is using local files and it's because I would like to use CDN. I did nothing special, so I'm really lost I'm just following a basic example.

**Comment by suren-atoyan** [comment] 2020-04-23 21:57
> What is the difference between
> 
> ```js
> monaco.config({
>   urls: {
>     monacoLoader: "/vs/loader.js",
>     monacoBase: "/vs"
>   }
> });
> ```
> 
> and
> 
> ```js
> monaco.config({
>   paths: {
>     vs: '...',
>   },
>   'vs/nls' : {
>     availableLanguages: {
>       '*': 'de',
>     },
>   },
> });
> ```

you can compare

this one

```js
monaco.config({
  urls: {
    monacoLoader: '/vs/loader.js',
    monacoBase: '/vs'
  }
});
```
and 

```js
monaco.config({
  paths: {
    vs: '/vs',
  }
});
```

this one ('vs/nls' is about localization).

And they are identical from a technical point of view; just the first one is deprecated in the last version (the second one is the new way to configure it).

**Comment by suren-atoyan** [comment] 2020-04-23 22:00
> @suren-atoyan I have tried this of course. I'm using the same cdn link that your demo,
> <img alt="Screenshot 2020-04-23 at 21 36 51" width="1680" src="https://user-images.githubusercontent.com/8804297/80141979-bb357a00-85aa-11ea-9ab3-2c24a703908d.png">
> 
> But still the same issue so I don't understand.
> <img alt="Screenshot 2020-04-23 at 21 38 54" width="618" src="https://user-images.githubusercontent.com/8804297/80142138-f9cb3480-85aa-11ea-95be-c9ae53b032f6.png">
> 
> I downgraded to use the same version as you on the demo, the 3.1.0. Same issue. The only thing I didn't tried is using local files and it's because I would like to use CDN. I did nothing special, so I'm really lost I'm just following a basic example.
> 
> I have the same problem with any CDN. There is something wrong on my side. Well I will keep investigate.

Is it possible to provide a reproducible snippet?

If no, so, please:

1) provide some information about your environment (browser, browser version, os, etc.)
2) check your extensions, try it in incognito mode for example.
3) check the flags in the chrome (maybe you have disabled workers)

**Comment by benjaminbours** [comment] 2020-04-24 06:16
I'm not in a CRA environment. https://create-react-app.dev/docs/making-a-progressive-web-app/ . It should be an issue about workers configuration. I have a big hole in my knowledge about workers, time to fill it. Thanks anyway and sorry for bothering you. :)

**Comment by martonlanga** [comment] 2021-01-19 19:15
> new CopyWebpackPlugin([
  { from: "node_modules/monaco-editor/min/vs/", to: "vs" },
  //{ from: "node_modules/monaco-editor/min-maps/vs/", to: "min-maps/vs" } // source-maps
]),

@elisherer I see you tried to include the source maps as well. Did that work for you? I'm still getting warning saying `DevTools failed to parse SourceMap`.

Only could make them disappear by disabling Javascript Source Maps in chrome settings.

**Comment by elisherer** [comment] 2021-01-20 07:29
@martonlanga , I see it does work as I written it,
In my code it is conditioned to be on when in development mode:
```js
    new CopyWebpackPlugin({
      patterns: [
        { from: "public", to: "." },
        { from: "node_modules/monaco-editor/min/vs/", to: "vs" },
        !PRODUCTION && { from: "node_modules/monaco-editor/min-maps/vs/", to: "min-maps/vs" }
      ].filter(Boolean)
    })
```
Maybe you are missing the initialization?
```js
monaco.config({
  paths: {
    vs: "/vs"
  }
});
```

**Comment by martonlanga** [comment] 2021-01-21 13:51
@elisherer Alright, thanks for your answer!

Everything including init is working fine, except source-maps.

I'm using Snowpack, maybe it has something to do with that.

**Comment by dmitryshelomanov** [comment] 2022-02-03 16:49
still can not be taken from the modules ?

**Comment by elisherer** [comment] 2022-02-03 17:11
If using webpack, use [`monaco-editor-webpack-plugin`](https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin) (official plugin by Microsoft)

**Comment by dmitryshelomanov** [comment] 2022-02-03 21:17
not working
langs provided by external scripts (not from node_modules)

**Comment by suren-atoyan** [comment] 2022-06-27 21:22
@NxRoot could you please

instead of this:

```js
import * as monaco from 'monaco-editor'
import Editor, { loader } from "@monaco-editor/react"
const path = window.require("path") // remember to set contextIsolation to false

function ensureFirstBackSlash(str) {
  return str.length > 0 && str.charAt(0) !== "/"
      ? "/" + str
      : str;
}

function uriFromPath(_path) {
  const pathName = path.resolve(_path).replace(/\\/g, "/");
  return encodeURI("file://" + ensureFirstBackSlash(pathName));
}

loader.config({
  paths: {
    vs: uriFromPath(
      path.join(__dirname, "../node_modules/monaco-editor/min/vs")
    )
  },
  monaco // the real solution is here, injecting monaco into loader
});

export default function App() {
  return (
   <Editor
     height="90vh"
     defaultLanguage="javascript"
     defaultValue="// some comment"
   />
  );
}
```

try just this:

```js
import * as monaco from 'monaco-editor'
import Editor, { loader } from "@monaco-editor/react"

loader.config({ monaco });

export default function App() {
  return (
   <Editor
     height="90vh"
     defaultLanguage="javascript"
     defaultValue="// some comment"
   />
  );
}
```

Once you set `monaco` in the config, other config fields will be ignored, so, no need to have `loader.config({ path: ... })`

**Comment by NxRoot** [comment] 2022-06-27 23:51
@suren-atoyan Thank you very much, its working!
> 
> ```js
> import * as monaco from 'monaco-editor'
> import Editor, { loader } from "@monaco-editor/react"
> 
> loader.config({ monaco });
> 
> export default function App() {
>   return (
>    <Editor
>      height="90vh"
>      defaultLanguage="javascript"
>      defaultValue="// some comment"
>    />
>   );
> }
> ```
> 
> Once you set `monaco` in the config, other config fields will be ignored, so, no need to have `loader.config({ path: ... })`

**Comment by vinodronold** [comment] 2022-09-02 10:15
import * as monaco from 'monaco-editor'
import Editor, { loader } from "@monaco-editor/react"

loader.config({ monaco });

export default function App() {
  return (
   <Editor
     height="90vh"
     defaultLanguage="javascript"
     defaultValue="// some comment"
   />
  );
}

This should be part of the documentation for electron users.

**Comment by twigs67** [comment] 2023-05-15 23:10
This looked like such a sweet solution, but unfortunately it did not work for me. I'm getting this error:

```
Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (http://localhost:3000/static/js/vendors-node_modules_mui_material_CardHeader_CardHeader_js-node_modules_monaco-editor_esm_vs_-88dd7c.chunk.js:98341:27)
    at http://localhost:3000/static/js/vendors-node_modules_mui_material_CardHeader_CardHeader_js-node_modules_monaco-editor_esm_vs_-88dd7c.chunk.js:54028:22
    at async http://localhost:3000/static/js/vendors-node_modules_monaco-editor_esm_vs_language_typescript_tsMode_js.chunk.js:131:16
    at async WorkerManager.getLanguageServiceWorker (http://localhost:3000/static/js/vendors-node_modules_monaco-editor_esm_vs_language_typescript_tsMode_js.chunk.js:137:20)
    at async DiagnosticsAdapter._doValidate (http://localhost:3000/static/js/vendors-node_modules_monaco-editor_esm_vs_language_typescript_tsMode_js.chunk.js:427:20)
Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (http://localhost:3000/static/js/vendors-node_modules_mui_material_CardHeader_CardHeader_js-node_modules_monaco-editor_esm_vs_-88dd7c.chunk.js:98341:27)
    at http://localhost:3000/static/js/vendors-node_modules_mui_material_CardHeader_CardHeader_js-node_modules_monaco-editor_esm_vs_-88dd7c.chunk.js:54028:22
    at async http://localhost:3000/static/js/vendors-node_modules_monaco-editor_esm_vs_language_typescript_tsMode_js.chunk.js:131:16
    at async WorkerManager.getLanguageServiceWorker (http://localhost:3000/static/js/vendors-node_modules_monaco-editor_esm_vs_language_typescript_tsMode_js.chunk.js:137:20)
    at async DiagnosticsAdapter._doValidate (http://localhost:3000/static/js/vendors-node_modules_monaco-editor_esm_vs_language_typescript_tsMode_js.chunk.js:427:20)
    at http://localhost:3000/static/js/vendors-node_modules_mui_material_CardHeader_CardHeader_js-node_modules_monaco-editor_esm_vs_-88dd7c.chunk.js:27337:17
```

after trying:
```
import * as monaco from 'monaco-editor'
import Editor, { loader } from "@monaco-editor/react"

loader.config({ monaco });
```
As others have suggested. Any thoughts? Next step is to eject CRA and use the MonacoWebpackPlugin

**Comment by elisherer** [comment] 2023-05-16 14:55
I suggest using [`customize-cra`](https://www.npmjs.com/package/customize-cra) (instead of ejecting)

Example `config-overrides.js`
```js
const { override, addWebpackPlugin } = require("customize-cra");
const MonacoEditorWebpackPlugin = require("monaco-editor-webpack-plugin");

module.exports = {
  webpack: override(
    addWebpackPlugin(
      new MonacoEditorWebpackPlugin({
        languages: ["javascript", "json", "xml"],
      })
    )
  )
};  
```

**Comment by vocoWone** [comment] 2023-08-11 11:00
> set `monaco` in the config, other config fields will be ignored

 hi @suren-atoyan s After setting `loader.config({ monaco })`, `options` fields is invalid. how can i fix it?😅

e.g:
``` 
import * as monaco from 'monaco-editor';
import Editor, { loader } from '@monaco-editor/react';

loader.config({ monaco });

<Editor language="json" options={{autoIndent: 'advanced'}} />
```

**Comment by xiaopujun** [comment] 2023-11-08 04:48
> Hi guys. The new version is here. (v1.2.0).
> 
> You can modify config as shown [here](https://github.com/SurenAt93/monaco-react/blob/master/README.md#config).
> 
> #### For downloading monaco from your files
> So, if you are using CRA, for example, you can install `monaco-editor` package:
> 
> ```shell
> yarn add monaco-editor # (npm install monaco-editor)
> ```
> 
> after that move/copy the minified (it's for an example) version of editor to your (CRA) public folder:
> 
> ```shell
> mv node_modules/monaco-editor/min/vs/ ./public
> ```
> 
> and now, by changing configs with the new api, you can load monaco files from your public folder:
> 
> ```js
> import { monaco } from '@monaco-editor/react';
> 
> monaco
>   .config({
>     urls: {
>       monacoLoader: '/vs/loader.js',
>       monacoBase: '/vs'
>     },
>   });
> ```
> 
> Please check it and let me know if it covers your cases. Thank you!

Hi suren, thanks for making this React version of Monaco editor. it simplifies my work a lot.

I can't load monaco editor using cdn due to usage scenario. So I need to load it locally. I used CRA. and processed it as you described above. But I found that

 import { monaco } from '@monaco-editor/react'.

There seems to be an error, I sent this to import the monaco instance directly for configuration.

The version I'm using is "@monaco-editor/react": "4.2.1", which is a fairly late version, and I'm not sure if there are any major differences in usage between that and the v1.2.0 version provided above.

Also my project is based on TypeScript. this may be one of the influencing factors. Hope to get your reply.


Thank you!


This is my code:


![image](https://github.com/suren-atoyan/monaco-react/assets/38376350/4dd39496-0a79-4f55-8276-eda63a22abd8)

**Comment by elisherer** [comment] 2023-11-08 07:10
> > Hi guys. The new version is here. (v1.2.0).
> > You can modify config as shown [here](https://github.com/SurenAt93/monaco-react/blob/master/README.md#config).
> > #### For downloading monaco from your files
> > So, if you are using CRA, for example, you can install `monaco-editor` package:
> > ```shell
> > yarn add monaco-editor # (npm install monaco-editor)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after that move/copy the minified (it's for an example) version of editor to your (CRA) public folder:
> > ```shell
> > mv node_modules/monaco-editor/min/vs/ ./public
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and now, by changing configs with the new api, you can load monaco files from your public folder:
> > ```js
> > import { monaco } from '@monaco-editor/react';
> > 
> > monaco
> >   .config({
> >     urls: {
> >       monacoLoader: '/vs/loader.js',
> >       monacoBase: '/vs'
> >     },
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please check it and let me know if it covers your cases. Thank you!
> 
> Hi suren, thanks for making this React version of Monaco editor. it simplifies my work a lot.
> 
> I can't load monaco editor using cdn due to usage scenario. So I need to load it locally. I used CRA. and processed it as you described above. But I found that
> 
> import { monaco } from '@monaco-editor/react'.
> 
> There seems to be an error, I sent this to import the monaco instance directly for configuration.
> 
> The version I'm using is "@monaco-editor/react": "4.2.1", which is a fairly late version, and I'm not sure if there are any major differences in usage between that and the v1.2.0 version provided above.
> 
> Also my project is based on TypeScript. this may be one of the influencing factors. Hope to get your reply.
> 
> Thank you!
> 
> This is my code:
> 
> ![image](https://user-images.githubusercontent.com/38376350/281263800-4dd39496-0a79-4f55-8276-eda63a22abd8.png)

try 
```typescript
import type { Monaco } from "@monaco-editor/react";
```

**Comment by xiaopujun** [comment] 2023-11-08 07:18
it means I need to switch the version to v1.2.0 and then tweak it the way you provided 

@elisherer

**Comment by arkitwg** [comment] 2023-12-28 10:54
Hi @suren-atoyan , I've electron app where have to load files from `file:/` instead of CDN. I've tried the above solution with latest version but still getting below error:

`
Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule
`

**Comment by arshad-yaseen** [comment] 2024-06-21 10:15
> Hi @suren-atoyan , I've electron app where have to load files from `file://` instead of CDN. I've tried the above solution with latest version but still getting below error:
> 
> ```
> Uncaught Error: Unexpected usage
> 
> Error: Unexpected usage
>     at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?39ad:492:1)
>     at eval (webWorker.js?e579:38:1)
>     at async eval (tsMode.js?3397:88:1)
>     at eval (errors.js?6fb9:15:1)
> ```
> 
> Could you please help me out this, thanks!

I have the same issue in React, Please @suren-atoyan help us!

**Comment by maxhudson** [comment] 2024-07-31 15:40
> > Hi @suren-atoyan , I've electron app where have to load files from `file://` instead of CDN. I've tried the above solution with latest version but still getting below error:
> > ```
> > Uncaught Error: Unexpected usage
> > 
> > Error: Unexpected usage
> >     at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?39ad:492:1)
> >     at eval (webWorker.js?e579:38:1)
> >     at async eval (tsMode.js?3397:88:1)
> >     at eval (errors.js?6fb9:15:1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you please help me out this, thanks!
> 
> I have the same issue in React, Please @suren-atoyan help us!

+1 running into this as well -- @suren-atoyan any guidance? We really want to use monaco over codemirror!

**Comment by suren-atoyan** [comment] 2024-08-01 05:07
@maxhudson @arshad-yaseen could you please try to use it as [an npm package](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#use-monaco-editor-as-an-npm-package) instead of CDN or file://?

**Comment by maxhudson** [comment] 2024-08-01 17:51
Thanks for getting back to me.

I was able to resolve with a bit of a "hack": https://stackoverflow.com/questions/64243893/monaco-editor-console-error-unexpected-usage-at-editorsimpleworker-loadforeignm/78822354#78822354

In our case though, using electron, we have good access to webpack, so we switched from using this react library to using the raw `monaco-editor` package (which we need anyway to avoid the CDN) and the `monaco-editor-webpack-plugin` - but I know this works well for web-browser use, and have used it before, so thank you for the package!
